### PR TITLE
Add logo snippet

### PR DESCRIPTION
**Pull request by fmerian**
This snippet helps users get any company logo with the Clearbit Company Logo API. Learn more: https://clearbit.com/blog/logo

### CODE REVIEW

**Comment by peduarte** [comment]
I dont understand this. What's it supposed to do?

**Comment by fmerian** [comment]
Hey Pedro! This snippet helps you get any company logo. For example, you can use it to quickly customize your Notion pages with your company logo. Try it yourself: https://logo.clearbit.com/raycast.com — and please keep me posted :)

**Comment by peduarte** [comment]
Ooooh ok. I think it's a bit too specific for this project. I'd like to try and keep the snippets for very well known things. But great to discover this API, very useful indeed! Thanks for your contribution 🙏

**Comment by fmerian** [comment]
Got it. Thanks for your feedback, and keep up your great work 🙂

**Pull request closed without merging**
