### PR TITLE
add ISO 8601 snippets

### PR DESCRIPTION
**Pull request by nagauta**
I added ISO 8601 snippets for Date & Time.

### CODE REVIEW

**Review by peduarte — APPROVED** [review]

**Comment by nagauta** [comment]
> 
Thanks. I use them personally but name this snippet "now", "now-" locally.
this is public so I rename to sounds formal
yeah they look too hard to type...

**Comment by peduarte** [comment]
haha yeah, maybe it's fine. 

one last thing: can we update the `text` so it's contextual. Refer to other date snippets, eg: "1 Year from Today", etc.

**Comment by nagauta** [comment]
sure, how about
Today is {date "yyyyMMdd"}.
Today is {date "yyyy-MM-dd"}.
or
I send you a Minutes{date "yyyyMMdd"}.pdf
I send you a Minutes-{date "yyyy-MM-dd"}.pdf

**Comment by peduarte** [comment]
@nagauta Hmm, not sure they make sense. specially because `{date "yyyyMMdd"}` will output `20230125` which just looks like a long number. Not sure people read dates like this. This is more useful as a kind of timestamp. 

If you cant think of real life use cases for this right now, we can close the PR and re-open later, but I think we need to make sure the snippets are clear and make sense at first glance to not confuse people.

Thanks!

**Comment by nagauta** [comment]
You are right. let me close PR now.
I use this when I write some code or SQL but I cant think of real life use cases for this right now.

**Pull request closed without merging**
